@startuml 'Sistema de Matrícula'
left to right direction
actor "Aluno" as aluno
actor "Secretaria" as secretaria
actor "Professor" as professor

rectangle "Sistema de matrícula"{
  usecase "Realizar matrícula" as realizarMatricula
  usecase "Cancelar matrícula" as cancelarMatricula

  usecase "Cancelar disciplina" as cancelarDisciplina
  usecase "Gerenciar disciplinas" as gerenciarDisciplinas
  usecase "Gerenciar professores" as gerenciarProfessores
  usecase "Gerenciar Alunos" as gerenciarAlunos
  usecase "Gerenciar cursos" as gerenciarCursos

  usecase "Notificar Sistema de Cobranças" as notificarCobranca
  usecase "Verificar numero de alunos" as verificarNumeroAlunos

  usecase "Consultar alunos" as consultarAlunos
}

professor -- consultarAlunos

aluno -- realizarMatricula
aluno -- cancelarMatricula

realizarMatricula ..> notificarCobranca : "<<include>>"
cancelarMatricula ..> notificarCobranca : "<<include>>"

gerenciarDisciplinas ..> verificarNumeroAlunos : "<<include>>"
verificarNumeroAlunos <. cancelarDisciplina : "<<extend>>"

secretaria -- gerenciarDisciplinas
secretaria -- gerenciarProfessores
secretaria -- gerenciarAlunos
secretaria -- gerenciarCursos
@enduml
